export enum ROUTES {
  Authentication = 'Authentication',
  Login = 'Login',
  Main = 'Main',
  Splash = 'Splash',
  Home = 'Home',
  CredentialCollector = 'CredentialCollector',
  InvestorInfoCollector = 'InvestorInfoCollector',
  MultipleChoiceCollector = 'MultipleChoiceCollector',
  Trade = 'Trade',
  Me = 'Me',
  Onboarding = 'Onboarding',
  TradingExperience = 'TradingExperience',
  MoneyManagement = 'MoneyManagement',
  TradingHorizon = 'TradingHorizon',
  ThreeMPurpose = 'ThreeMPurpose',
  Tradier = 'Tradier',
  SearchResults = 'SearchResults',
  TradeForm = 'TradeForm',
  FormResults = 'FormResults',
}
